ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

DROP USER concesionario CASCADE;

CREATE USER concesionario IDENTIFIED BY "Med@c"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA 100M ON USERS;


GRANT CONNECT, RESOURCE TO concesionario;

